### ISSUE TITLE
Add unit algorithm option

### ISSUE THREAD

**Issue by wieslawsoltes** [daltonks/BitmapToVector#1]
```
 -u, --unit n               - quantize output to 1/unit pixels (default 10)
```

**Comment by daltonks** [comment]
Looking at Potrace's `backend_svg.c`, it seems easy enough to figure out unit quantization. I'll give it a try 👍

**Comment by daltonks** [comment]
Version 1.62.2 has quantization with `PotraceParam.QuantizeUnit`. The NuGet packages are validating now.
Let me know if this is what you were looking for!
https://github.com/daltonks/BitmapToVector/commit/cfc084c98588559af0f1c72facf3520f1b747524

**Comment by daltonks** [comment]
Is this to lower the size of SVG data? If so, you could multiply each point by 10 and floor the values. Then add a transform to the SVG that scales everything by .1. That's how potrace's `backend_svg.c` does it.

**Comment by wieslawsoltes** [comment]
> Is this to lower the size of SVG data? If so, you could multiply each point by 10 and floor the values. Then add a transform to the SVG that scales everything by .1. That's how potrace's `backend_svg.c` does it.

I will take a look at potrace's svg backend.
