### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by selinger** [daltonks/BitmapToVector#3]
Hi Daltonks,

sorry for contacting you via a GitHub issue; I sent you an email and got a bounce message saying the domain no longer exists. I don't have alternative contact information for you. Can you please get in touch we me? 

Thanks, -- Peter from Potrace

**Comment by daltonks** [comment]
Sorry about that, I'll do so today! I'll try to find the same email address that I was sending to before.

**Comment by daltonks** [comment]
I shot you an email!
